routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/medecin', 'Auth\MedecinLoginController@showLoginForm')->name('medecin-login');
Route::post('/medecin', ['as'=> 'medecin-login','uses'=>'Auth\MedecinLoginController@login']);
Route::prefix('medecin')->group(function(){
	Route::name('medecin.')->group(function () {
		Route::get('/home', 'MedecinController@index' )->name('index');

		Route::post('/create_ordonnance', 'MedecinController@createOrdonnance' )->name('create_ordonnance');
		Route::post('/add_prescription', 'MedecinController@addPrescription' )->name('add_prescription');
		Route::get('/send_ordonnance/{ordonnance}', 'MedecinController@sendOrdonnance' )->name('send_ordonnance');
		Route::get('/list_ordonnance', 'MedecinController@listOrdonnance' )->name('list_ordonnance');
		Route::get('/list_ordonnance_archivee', 'MedecinController@listOrdonnanceArchivee' )->name('list_ordonnance_archivee');


		






		// Déconnexion prof
		Route::post('/medecin-logout',function(){
			auth()->logout();
			return redirect()->route('medecin-login');
		})->name('logout');
	});
});

Route::get('/home', 'PharmacieController@index')->name('home');
Route::get('/archiver_ordonnance/{ordonnance}', 'PharmacieController@archiverOrdonnance' )->name('archiver_ordonnance');
		Route::get('/list_ordonnance', 'PharmacieController@listOrdonnance' )->name('list_ordonnance');
		Route::get('/list_ordonnance_archivee', 'PharmacieController@listOrdonnanceArchivee' )->name('list_ordonnance_archivee');

		Route::get('/show_medicament', 'PharmacieController@showMedicament' )->name('show_medicament');








Route::get('/view_ordonnance/{ordonnance}', 'MedecinController@viewOrdonnance' )->name('view_ordonnance');

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row">
       {{--  <div class="col-sm-4">
            <div class="card text-center text-white bg-success mb-3" style="max-width: 18rem;">
              <div class="card-body">
                <button type="button" class="addModal btn btn-success" data-toggle="modal" data-target="#exampleModal" >
                    <h5 class="card-title " ><i class="fas fa-plus-circle fa-2x"></i></h5>
                    <h5 class="card-text">NOUVELLE ORDONNACE</h5>
                </button>
              </div>
            </div>
        </div> --}}
        <div class="col-sm-4">
            <div class="card text-center text-white bg-success mb-3" style="max-width: 18rem;">
              {{-- <div class="card-header">Header</div> --}}
              <div class="card-body">
                <a href="{{ route('show_medicament') }}" class="btn btn-success">
                    <h5 class="card-title " ><i class=" fas fa-capsules fa-2x"></i></h5>
                    <h5 class="card-text">STOCK MEDICAMENTS</h5>
                </a>
              </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card text-center text-white bg-success mb-3" style="max-width: 18rem;">
              {{-- <div class="card-header">Header</div> --}}
              <div class="card-body">
                <a href="#" class="btn btn-success">
                    <h5 class="card-title " ><i class=" fas fa-file fa-2x"></i></h5>
                    <h5 class="card-text">ORDONNANCES </h5>
                </a>
              </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card text-center text-white bg-success mb-3" style="max-width: 18rem;">
              {{-- <div class="card-header">Header</div> --}}
              <div class="card-body">
                <a href="#" class="btn btn-success">
                    <h5 class="card-title " ><i class=" fas fa-archive fa-2x"></i></h5>
                    <h5 class="card-text">ARCHIVES ORDONNACES</h5>
                </a>
              </div>
            </div>
        </div>
    </div>
</div>
@include('partials.includes.formulaires._add_ordonnance')

@endsection

resources/views/view_ordonnance.blade.php
@extends('layouts.master')
@section('content')
<div class="card">
	<div class="card-body">
		<div class="card">
			<div class="card-body">
				<div class="container">
					@if(App\Models\Prescription::byOrdonnance($ordonnance->idordonnances)->count() > 0 || auth('medecin')->user()->idmedecins == $ordonnance->idmedecins)
					<table class="table table-striped table-bordered">
					  <thead>
					    <tr>
					      <th scope="col">#</th>
					      <th scope="col">Designation</th>
					      <th scope="col">Quantité</th>
					      <th scope="col">Description</th>
					    </tr>
					  </thead>
					  	
					  <tbody>
					  	@php $i=1; @endphp
					  	@foreach(App\Models\Prescription::byOrdonnance($ordonnance->idordonnances) as $p)
					    <tr>
					      <th scope="row">{{ $i++ }}</th>
					      <td>{{ $p->lib }}</td>
					      <td>{{ $p->quantite }}</td>
					      <td>{{ $p->description }}</td>
					    </tr>
					    @endforeach
					  </tbody>
					</table>
				</div>	
				@if(auth('medecin')->user()->idmedecins == $ordonnance->idmedecins && $ordonnance->statut == 'en_cours')
				<div class="float-right">
					<button  class="btn btn-outline-success" data-toggle="modal" data-target="#prescriptionModal" >AJOUTER UNE PRESCRIPTION</button>
					<a href="{{ route('medecin.send_ordonnance',$ordonnance->idordonnances) }}" class="btn btn-outline-success">ENVOYER L'ORDONNANCE</a>
				</div>
				@include('partials.includes.formulaires._add_prescription')
				@endif
			</div>
			
			<div class="card-footer">
				<div class="float-right">{{ $ordonnance->updated_at }}</div>
			</div>
			@else
			@if($ordonnance == "en_cours")
				<div class="d-flex justify-content-center">
					<button  class="btn btn-outline-success" data-toggle="modal" data-target="#prescriptionModal" >AJOUTER UNE PRESCRIPTION</button>
				</div>
			@else
			<div class="d-flex justify-content-center">
					<button  class="btn btn-outline-success" >Aucune prescription disponible</button>
				</div>
			@endif
			@endif
		</div>
		
	</div>
</div>
@include('partials.includes.formulaires._add_prescription')

@endsection