routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/medecin', 'Auth\MedecinLoginController@showLoginForm')->name('medecin-login');
Route::post('/medecin', ['as'=> 'medecin-login','uses'=>'Auth\MedecinLoginController@login']);
Route::prefix('medecin')->group(function(){
	Route::name('medecin.')->group(function () {
		Route::get('/home', 'MedecinController@index' )->name('index');

		Route::post('/create_ordonnance', 'MedecinController@createOrdonnance' )->name('create_ordonnance');
		Route::post('/add_prescription', 'MedecinController@addPrescription' )->name('add_prescription');
		Route::get('/send_ordonnance/{ordonnance}', 'MedecinController@sendOrdonnance' )->name('send_ordonnance');
		Route::get('/list_ordonnance', 'MedecinController@listOrdonnance' )->name('list_ordonnance');
		Route::get('/list_ordonnance_archivee', 'MedecinController@listOrdonnanceArchivee' )->name('list_ordonnance_archivee');


		






		// Déconnexion prof
		Route::post('/medecin-logout',function(){
			auth()->logout();
			return redirect()->route('medecin-login');
		})->name('logout');
	});
});

Route::get('/home', 'PharmacieController@index')->name('home');
Route::get('/archiver_ordonnance/{ordonnance}', 'PharmacieController@archiverOrdonnance' )->name('archiver_ordonnance');
		Route::get('/list_ordonnance', 'PharmacieController@listOrdonnance' )->name('list_ordonnance');
		Route::get('/list_ordonnance_archivee', 'PharmacieController@listOrdonnanceArchivee' )->name('list_ordonnance_archivee');

		Route::get('/show_medicament', 'PharmacieController@showMedicament' )->name('show_medicament');








Route::get('/view_ordonnance/{ordonnance}', 'MedecinController@viewOrdonnance' )->name('view_ordonnance');

app/Models/Medecin.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Medecin extends Authenticatable
{
    use Notifiable;
    protected $primaryKey = 'idmedecins';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'pseudo', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/MedecinController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Patient;
use App\Models\Medecin;
use App\Models\Ordonnance;
use App\Models\Prescription;

use App\DataTables\Medecins\ListeOrdonanceDataTable;
use App\DataTables\Medecins\ListOrdonnanceArchiveeDataTable;
use App\Http\Requests\CreateOrdonnanceRequest;
use App\Http\Requests\AddPrescriptionRequest;
use Flashy;

class MedecinController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth:medecin')->except(['viewOrdonnance']);
    }
    public function index(){
    	return view('medecin.index');
    }

    public function createOrdonnance(CreateOrdonnanceRequest $request){
    	$ordonnance = Ordonnance::create($request->except('_token'));
        Flashy::message('Ordonnance créee avec succès');
        return redirect()->route('view_ordonnance',$ordonnance->idordonnances);
    }

    public function viewOrdonnance(Ordonnance $ordonnance){
        return view('view_ordonnance',compact('ordonnance'));
    }

    public function addPrescription(AddPrescriptionRequest $request){
        $prescription = Prescription::updateOrCreate($request->except('_token'));
        Flashy::message('Prescription ajoutér avec succès');
        return redirect()->route('view_ordonnance',$prescription->idordonnances);
    }

    public function sendOrdonnance(Ordonnance $ordonnance){
        $ordonnance->statut = "envoyer";
        $ordonnance->save();
        Flashy::message('Ordonnance envoyer avec succès');
        return redirect()->route('view_ordonnance',$ordonnance->idordonnances);

    }

    public function listOrdonnance(ListeOrdonanceDataTable $dataTable){
        return $dataTable->with(["idmedecins"=>auth()->user()->idmedecins])->render('medecin.list_ordonnance');
    }

    public function listOrdonnanceArchivee(ListOrdonnanceArchiveeDataTable $dataTable){
        return $dataTable->with(["idmedecins"=>auth()->user()->idmedecins])->render('medecin.list_ordonnance');
    }
}

resources/views/medecin/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="card text-center text-white bg-success mb-3" style="max-width: 18rem;">
              {{-- <div class="card-header">Header</div> --}}
              <div class="card-body">
                <button type="button" class="addModal btn btn-success" data-toggle="modal" data-target="#exampleModal" >
                    <h5 class="card-title " ><i class="fas fa-plus-circle fa-2x"></i></h5>
                    <h5 class="card-text">NOUVELLE ORDONNACE</h5>
                </button>
              </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card text-center text-white bg-success mb-3" style="max-width: 18rem;">
              {{-- <div class="card-header">Header</div> --}}
              <div class="card-body">
                <a href="{{ route('medecin.list_ordonnance') }}" class="btn btn-success">
                    <h5 class="card-title " ><i class=" fas fa-file fa-2x"></i></h5>
                    <h5 class="card-text">ORDONNANCES</h5>
                </a>
              </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card text-center text-white bg-success mb-3" style="max-width: 18rem;">
              {{-- <div class="card-header">Header</div> --}}
              <div class="card-body">
                <a href="{{ route('medecin.list_ordonnance_archivee') }}" class="btn btn-success">
                    <h5 class="card-title " ><i class=" fas fa-archive fa-2x"></i></h5>
                    <h5 class="card-text">ARCHIVES ORDONNACES</h5>
                </a>
              </div>
            </div>
        </div>
    </div>
</div>
@include('partials.includes.formulaires._add_ordonnance')

@endsection

resources/views/medecin/list_ordonnance.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')

<div class="row d-flex justify-content-center">
    <div class="col-10">
        <div class="card">

            {{-- <div class="card-header">DDDDD</div> --}}
            <div class="card-body ">
                @auth('medecin')
                <div class="row">
                    <div class="col">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >
                          <i class="fa fa-plus"></i> Nouvelle ordonnance
                        </button>
                    </div>
                </div>
                @include('partials.includes.formulaires._add_ordonnance')
                @endauth
                 {!!$dataTable->table() !!}
            </div>
        </div>
    </div>
</div>



@endsection
@push('scripts')
  {!!$dataTable->scripts() !!}
  
@endpush

resources/views/medecin/list_ordonnance_archivee.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')

<div class="row d-flex justify-content-center">
    <div class="col-10">
        <div class="card">

            {{-- <div class="card-header">DDDDD</div> --}}
            <div class="card-body ">
                @auth('medecin')
                <div class="row">
                    <div class="col">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" >
                          <i class="fa fa-plus"></i> Nouvelle ordonnance
                        </button>
                    </div>
                </div>
                @include('partials.includes.formulaires._add_ordonnance')
                @endauth
                 {!!$dataTable->table() !!}
            </div>
        </div>
    </div>
</div>



@endsection
@push('scripts')
  {!!$dataTable->scripts() !!}
  
@endpush